@url = http://localhost:5000

###
GET {{url}}

###
GET {{url}}/Reservations

###
GET {{url}}/Reservations/1

###
Post {{url}}/Reservations
Content-Type: application/json

{
    "EmployeeName": "John Doe",
    "ParkingSpotName": "P3",
    "LicensePlate": "XYZ123"
}

###
PUT {{url}}/Reservations/1
Content-Type: application/json

{
    "LicensePlate": "XYZ111"
}

###
DELETE {{url}}/Reservations/1
