@url = http://localhost:5000
@reservationId = 00000000-0000-0000-0000-000000000001
@parkingSpotId = 00000000-0000-0000-0000-000000000001

###
POST {{url}}/users
Content-Type:application/json
{
  "email":"test@test.com",
  "username":"test",
  "password":"test",
  "fullname":"test",
  "role":"user",

}


###
GET {{url}}

###
GET {{url}}/parking-spots/reservations

###
GET {{url}}/parking-spots/reservations/{{reservationId}}

###
Post {{url}}/parking-spots/reservations/vehicle
Content-Type: application/json

{
    "parkingSpotId":"{{parkingSpotId}}",
    "EmployeeName": "John Doe",
    "Capacity": 1,
    "LicensePlate": "XYZ123",
    "date": "2025-08-05"
}

###
Post {{url}}/parking-spots/reservations/Cleaning
Content-Type: application/json

{
    "date": "2025-08-05"
}

###
PUT {{url}}parking-spots/reservations/{{reservationId}}
Content-Type: application/json

{
    "LicensePlate": "XYZ111"
}

###
DELETE {{url}}parking-spots/reservations/{{reservationId}}
Content-Type: application/json

{
    "parkingSpotId":{{parkingSpotId}},
}
