@url = http://localhost:5000
@reservationId = 00000000-0000-0000-0000-000000000001
@parkingSpotId = 00000000-0000-0000-0000-000000000001
###
GET {{url}}

###
GET {{url}}/reservations

###
GET {{url}}/reservations/{{reservationId}}

###
Post {{url}}/Reservations
Content-Type: application/json

{
    "parkingSpotId":"{{parkingSpotId}}",
    "EmployeeName": "John Doe",
    "LicensePlate": "XYZ123",
    "date": "2025-07-27"
}

###
PUT {{url}}/Reservations/{{reservationId}}
Content-Type: application/json

{
    "LicensePlate": "XYZ111"
}

###
DELETE {{url}}/Reservations/{{reservationId}}
Content-Type: application/json

{
    "parkingSpotId":{{parkingSpotId}},
}
