# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    shm_size: '4gb'
    environment:
      POSTGRES_PASSWORD: example
    ports:
        - 5432:5432
    volumes:
        - postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always

volumes:
  postgres:
    driver: local